# Generated by Django 5.2.7 on 2025-10-28 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時刻')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了時刻')),
                ('status', models.CharField(choices=[('running', '実行中'), ('completed', '完了'), ('failed', '失敗')], default='running', max_length=20, verbose_name='ステータス')),
                ('total_companies', models.IntegerField(default=0, verbose_name='総会社数')),
                ('processed_companies', models.IntegerField(default=0, verbose_name='処理済み会社数')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
            ],
            options={
                'verbose_name': '実行履歴',
                'verbose_name_plural': '実行履歴一覧',
                'ordering': ['-started_at'],
            },
        ),
    ]
