# Generated by Django 5.2.7 on 2025-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_executionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionhistory',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='max_companies',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大処理数'),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='spreadsheet_range',
            field=models.CharField(default='会社リスト!A3:D', max_length=100, verbose_name='スプレッドシート範囲'),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='update_google_sheets',
            field=models.BooleanField(default=True, verbose_name='Google Sheets更新'),
        ),
    ]
